version: '3.8'
services:
  web:
    build:
      context: . # where to find the project files
      dockerfile: dockerfile #the docker file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #path to ignore and not try to associate a volume for it
      - .:/app   # associate . from host with /app from the container

